name: parallel-update-step

on:
  workflow_call:
    inputs:
      step:
        description: 'Synchronized parallelism step number'
        required: true
        type: string
      prev_step_a:
        description: 'Previous step A for restoring shared resources (optional)'
        required: false
        default: ''
        type: string
      prev_step_b:
        description: 'Previous step B for restoring shared resources (optional)'
        required: false
        default: ''
        type: string
      is_commit:
        description: 'Push changes to remote (optional)'
        required: false
        default: ''
        type: string

permissions:
  actions: write
  contents: read

jobs:
  run-parallel-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        job: [1, 2, 3, 4]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          repository: ${{ secrets.REPO_NAME }}
          ref: main
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Python v3.13
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install dependencies
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: '1'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download shared resources from previous step A
        if: inputs.prev_step_a != ''
        uses: actions/download-artifact@v6
        with:
          pattern: step_${{ inputs.prev_step_a }}_job*
          path: _aggregate
          merge-multiple: true

      - name: Download shared resources from previous step B
        if: inputs.prev_step_b != ''
        uses: actions/download-artifact@v6
        with:
          pattern: step_${{ inputs.prev_step_b }}_job*
          path: _aggregate
          merge-multiple: true

      - name: Move shared resources from artifacts
        if: inputs.prev_step_a != ''
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          mkdir -p files
          mapfile -t hfsec < <(find _aggregate -type f -name '*.hfsec')
          if ((${#hfsec[@]})); then
            mv -f "${hfsec[@]}" files/
          fi

      - name: Configure args
        env:
          IS_MANUAL_OVERRIDE: ${{ secrets.IS_MANUAL_OVERRIDE }}
          MONTH_OVERRIDE: ${{ secrets.MONTH }}
          DAY_OVERRIDE: ${{ secrets.DAY }}
          HOUR_OVERRIDE: ${{ secrets.HOUR }}
        shell: bash
        run: |
          set -euo pipefail

          MONTH=$(date -u +%m)
          if [ "$MONTH" -eq 9 ]; then
            DAY=30
          elif [ "$MONTH" -eq 10 ]; then
            DAY=$(date -u +%d | sed 's/^0//')
          else
            MONTH=11
            DAY=1
          fi
          HOUR=$(date -u +%H)
  
          IS_MANUAL_OVERRIDE=${IS_MANUAL_OVERRIDE:-}
          MONTH_OVERRIDE=${MONTH_OVERRIDE:-}
          DAY_OVERRIDE=${DAY_OVERRIDE:-}
          HOUR_OVERRIDE=${HOUR_OVERRIDE:-}

          if [ "${IS_MANUAL_OVERRIDE,,}" == "true" ]; then
            if [ -n "$MONTH_OVERRIDE" ]; then 
              MONTH=$MONTH_OVERRIDE
            fi
            if [ -n "$DAY_OVERRIDE" ]; then 
              DAY=$DAY_OVERRIDE
            fi
            if [ -n "$HOUR_OVERRIDE" ]; then
              HOUR=$HOUR_OVERRIDE
            fi
          fi

          {
            echo "MONTH=$MONTH"
            echo "DAY=$DAY"
            echo "HOUR=$HOUR"
          } >> "$GITHUB_ENV"

      - name: Run step ${{ inputs.step }}
        env:
          GH_TOKEN: ${{ secrets[format('GH_TOKEN_{0}', matrix.job)] }}
          KEY: ${{ secrets.KEY }}
          JOB_ID: ${{ matrix.job }}
          NUM_JOBS: ${{ strategy.job-total }}
          STEP: ${{ inputs.step }}
          SLEEP_S: ${{ secrets.SLEEP_S }}
        run: |
          python hack_stats_pipeline.py \
            --month "$MONTH" --day "$DAY" --hour "$HOUR" \
            --job "${JOB_ID}" --jobs "${NUM_JOBS}" --step "${STEP}"

      - name: Move shared resources to artifacts
        if: inputs.step != '5'
        env:
          JOB_ID: ${{ matrix.job }}
          STEP: ${{ inputs.step }}
        run: |
          set -euo pipefail
          shopt -s nullglob
          mkdir -p "out/step_${STEP}_job_${JOB_ID}"
          matches=(files/step_${STEP}_job_$((10#$JOB_ID - 1))*.hfsec)
          if ((${#matches[@]})); then
            cp -f "${matches[@]}" "out/step_${STEP}_job_${JOB_ID}/"
          fi

      - name: Upload shared resources
        if: inputs.step != '5'
        uses: actions/upload-artifact@v5
        with:
          name: step_${{ inputs.step }}_job_${{ matrix.job }}
          path: out/step_${{ inputs.step }}_job_${{ matrix.job }}/
          if-no-files-found: ignore
          retention-days: 1

      - name: Commit
        if: inputs.is_commit != ''
        env:
          GH_TOKEN: ${{ secrets.REPO_TOKEN }}
          REPO: ${{ secrets.REPO_NAME }}
          JOB_ID: ${{ matrix.job }}
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          git add files/*.csv files/*.json || true
          if ! git diff --cached --quiet; then
            git config user.name "Adam Ross"
            git config user.email "14985050+R055A@users.noreply.github.com"
            git commit -m "Update $(date -u +'%Y') stats (${JOB_ID})"

            for attempt in 1 2 3; do
              git pull --rebase "https://x-access-token:${GH_TOKEN}@github.com/${REPO}.git" main || true
              if git push "https://x-access-token:${GH_TOKEN}@github.com/${REPO}.git" HEAD:main; then
                break
              fi
              echo "Push fail #$attempt..."
              sleep $(((RANDOM % 8) + 3))
            done
          fi
