name: update-stats

on:
  schedule:
    - cron: '0 11-23 30 9 *'
    - cron: '0 * * 10 *'
    - cron: '0 0-14 1 11 *'
  workflow_dispatch:

permissions:
  actions: write
  contents: read

concurrency:
  group: push-${{ github.ref }}
  cancel-in-progress: false

jobs:
  sync-parallel-fetch-step-1:
    uses: ./.github/workflows/sync_parallel_step.yml
    with:
      step: '1'
    secrets: inherit

  sync-parallel-fetch-step-2:
    needs: sync-parallel-fetch-step-1
    uses: ./.github/workflows/sync_parallel_step.yml
    with:
      step: '2'
      prev_step_a: '1'
    secrets: inherit

  sync-parallel-fetch-step-3:
    needs: sync-parallel-fetch-step-2
    uses: ./.github/workflows/sync_parallel_step.yml
    with:
      step: '3'
    secrets: inherit

  sync-parallel-fetch-step-4:
    needs: sync-parallel-fetch-step-3
    uses: ./.github/workflows/sync_parallel_step.yml
    with:
      step: '4'
      prev_step_a: '3'
    secrets: inherit

  sync-parallel-fetch-step-5:
    needs: [sync-parallel-fetch-step-2, sync-parallel-fetch-step-4]
    uses: ./.github/workflows/sync_parallel_step.yml
    with:
      step: '5'
      prev_step_a: '2'
      prev_step_b: '4'
      is_commit: 'true'
    secrets: inherit

  cleanup:
    runs-on: ubuntu-latest
    needs: sync-parallel-fetch-step-5

    steps:
      - name: Delete artifacts
        env:
          GITHUB_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
        run: |
          set -euo pipefail
          ids=$(gh api --paginate repos/$REPO/actions/runs/$RUN_ID/artifacts -q '.artifacts[].id')
          if [ -n "${ids:-}" ]; then
            for id in $ids; do
              echo "Deleting artifact id=$id"
              gh api -X DELETE repos/$REPO/actions/artifacts/$id || true
            done
          fi
